### ISSUE TITLE
When it fails the message doesn't help

### ISSUE THREAD

**Issue by nigelhorne** [PegasusPrime/fail2ban-etcd#1]
I get:

> Invalid response
> HTTP::Response=HASH(0xaaab028632f8)->decoded_content at ./fail2ban-pull line 12.

The patch is:

`*** foo	2018-07-22 10:24:03.596151251 -0400
--- fail2ban-pull	2018-07-22 10:24:19.876839069 -0400
***************
*** 9,15 ****
  $req->authorization_basic( "etcd", "bl0cked4u" );
  my $resp = $ua->request($req);
  if (! $resp->is_success) {
!  die "Invalid response\n$resp->decoded_content";
  }
  my $decode = decode_json($resp->content);
  
--- 9,15 ----
  $req->authorization_basic( "etcd", "bl0cked4u" );
  my $resp = $ua->request($req);
  if (! $resp->is_success) {
! 	die "Invalid response\n", $resp->decoded_content();
  }
  my $decode = decode_json($resp->content);`

Now I get:

> Invalid response
> Can't connect to [https:]:443 (Name or service not known)
> 
> Name or service not known at /usr/local/share/perl/5.24.1/LWP/Protocol/http.pm line 50.

Which is easier to debug.

**Comment by PegasusPrime** [comment]
Updated error message: https://github.com/PegasusPrime/fail2ban-etcd/commit/0787faea24d752809a6446a95330189a43f470c6#diff-24641e1c506cb218df09fa5b991ddfa3
